"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.4.
"""
import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kn6swbx=3tmcas944x8ar0$$*^8*%h+wxp0gamvslst!d$6dwq'

# SECURITY WARNING: don't run with debug turned on in production!
# Оставляем True, чтобы Django сам отдавал статику и медиа на Timeweb без сложной настройки Nginx
DEBUG = True 

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://rip88-sanatorium-diploma-1778.twc1.net',
    'http://rip88-sanatorium-diploma-1778.twc1.net',
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            ssl_require=False
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Язык и время
LANGUAGE_CODE = 'ru-RU'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

# Статические файлы (CSS, JS)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Указываем, где лежат исходные статические файлы (твои css, img в папке core/static)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Медиа файлы (картинки)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Убираем предупреждения о первичных ключах
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================
# ВАЖНО: Мы убрали блок с urlpatterns отсюда,
# так как он должен быть только в urls.py.
# Благодаря DEBUG = True, Django автоматически
# будет отдавать статику и медиа при запуске.
# ==========================================